const indianStates = [
  { option: "Uttar Pradesh" },
  { option: "Andaman and Nicobar Islands" },
  { option: "Andhra Pradesh" },
  { option: "Arunachal Pradesh" },
  { option: "Assam" },
  { option: "Bihar" },
  { option: "Chandigarh" },
  { option: "Chhattisgarh" },
  { option: "Dadra and Nagar Haveli" },
  { option: "Daman and Diu" },
  { option: "Delhi" },
  { option: "Goa" },
  { option: "Gujarat" },
  { option: "Haryana" },
  { option: "Himachal Pradesh" },
  { option: "Jammu and Kashmir" },
  { option: "Jharkhand" },
  { option: "Karnataka" },
  { option: "Kerala" },
  { option: "Ladakh" },
  { option: "Lakshadweep" },
  { option: "Madhya Pradesh" },
  { option: "Maharashtra" },
  { option: "Manipur" },
  { option: "Meghalaya" },
  { option: "Mizoram" },
  { option: "Nagaland" },
  { option: "Odisha" },
  { option: "Puducherry" },
  { option: "Punjab" },
  { option: "Rajasthan" },
  { option: "Sikkim" },
  { option: "Tamil Nadu" },
  { option: "Telangana" },
  { option: "Tripura" },
  { option: "Uttarakhand" },
  { option: "West Bengal" },
];
const regionData = [
  { id: "1", option: "Agra" },
  { id: "2", option: "Aligarh" },
  { id: "3", option: "Ayodhya" },
  { id: "4", option: "Azamgarh" },
  { id: "5", option: "Bareilly" },
  { id: "6", option: "Chitrakoot" },
  { id: "7", option: "Devipatan" },
  { id: "8", option: "Etawah" },
  { id: "9", option: "Ghaziabad" },
  { id: "10", option: "Gorakhpur" },
  { id: "11", option: "Hardoi" },
  { id: "12", option: "Jhansi" },
  { id: "13", option: "Kanpur" },
  { id: "14", option: "Lucknow" },
  { id: "15", option: "Meerut" },
  { id: "16", option: "Moradabad" },
  { id: "17", option: "Noida" },
  { id: "18", option: "Prayagraj" },
  { id: "19", option: "Saharanpur" },
  { id: "20", option: "Varanasi" },
];
const depotOptions = [
  { id: "1", option: "FORT" },
  { id: "2", option: "MATHURA" },
  { id: "3", option: "FOUNDARY NAGER" },
  { id: "4", option: "IDGAAH" },
  { id: "5", option: "TAJ" },
  { id: "6", option: "BAAH" },
  { id: "7", option: "HATHRAS" },
  { id: "8", option: "BUDDH VIHAR" },
  { id: "9", option: "NARAURA" },
  { id: "10", option: "ATRAULI" },
  { id: "11", option: "KASGANJ" },
  { id: "12", option: "ALIGARH" },
  { id: "13", option: "ETAH" },
  { id: "14", option: "AKBARPUR" },
  { id: "15", option: "SULTANPUR" },
  { id: "16", option: "AYODHYA" },
  { id: "17", option: "AMETHI" },
  { id: "18", option: "MAU" },
  { id: "19", option: "AZAMGARH" },
  { id: "20", option: "DOHRIGHAT" },
  { id: "21", option: "SHAHGANJ" },
  { id: "22", option: "AMBEDKAR NAGER" },
  { id: "23", option: "BALLIA" },
  { id: "24", option: "BELTHARA ROAD" },
  { id: "25", option: "BADAUN" },
  { id: "26", option: "BAREILLY" },
  { id: "27", option: "PILIBHIT" },
  { id: "28", option: "RUHELKHAND" },
  { id: "29", option: "BANDA" },
  { id: "30", option: "RATH" },
  { id: "31", option: "HAMIRPUR" },
  { id: "32", option: "MAHOBA" },
  { id: "33", option: "BAHRAICH" },
  { id: "34", option: "GONDA" },
  { id: "35", option: "BALRAMPUR" },
  { id: "36", option: "MAINPURI" },
  { id: "37", option: "AURAYA" },
  { id: "38", option: "ETAWAH/SAFAI" },
  { id: "39", option: "BEWAR/SHIBRAMAU" },
  { id: "40", option: "FARRUKHABAD" },
  { id: "41", option: "SHIKOHABAD" },
  { id: "42", option: "CHHIBRAMAU" },
  { id: "43", option: "SAHIBABAD" },
  { id: "44", option: "HAPUR" },
  { id: "45", option: "GHAZIABAD" },
  { id: "46", option: "LONI GZB" },
  { id: "47", option: "SIKANDRABAD" },
  { id: "48", option: "BULANDSHAHAR" },
  { id: "49", option: "KAUSHAMBI" },
  { id: "50", option: "KHURJA DEPOT" },
  { id: "51", option: "ANAD VIHAR-DELHI" },
  { id: "52", option: "AJMERI GATE DELHI" },
  { id: "53", option: "KASHMIRI GATE-ISBT (BSM)" },
  { id: "54", option: "KASHMIRI GATE-DELHI" },
  { id: "55", option: "PADRAUNA" },
  { id: "56", option: "SIDDHARTH NAGAR" },
  { id: "57", option: "SONAULI" },
  { id: "58", option: "NICHLAUL" },
  { id: "59", option: "DEORIA" },
  { id: "60", option: "GORAKHPUR" },
  { id: "61", option: "BASTI" },
  { id: "62", option: "RAPTI NAGAR" },
  { id: "63", option: "SHAHJAHANPUR" },
  { id: "64", option: "HARDOI" },
  { id: "65", option: "SITAPUR" },
  { id: "66", option: "GOLA" },
  { id: "67", option: "KANNUAJ" },
  { id: "68", option: "LAKHIMPUR" },
  { id: "69", option: "ORAI/JALAUN" },
  { id: "70", option: "JHANSI" },
  { id: "71", option: "AZADNAGAR" },
  { id: "72", option: "MATI" },
  { id: "73", option: "KIDWAI NAGAR" },
  { id: "74", option: "VIKAS NAGAR" },
  { id: "75", option: "FATEHPUR" },
  { id: "76", option: "FAZALGANG" },
  { id: "77", option: "B.S.M. JHAKARKATI" },
  { id: "78", option: "UNNAO" },
  { id: "79", option: "ALAMBAGH" },
  { id: "80", option: "CHARBAGH" },
  { id: "81", option: "KAISERBAGH" },
  { id: "82", option: "BARABANKI" },
  { id: "83", option: "AWADH" },
  { id: "84", option: "RAIBARIELLY" },
  { id: "85", option: "UPNAGARIA" },
  { id: "86", option: "B.S.M. ALAMBAGH" },
  { id: "87", option: "B.S.M. CHARBAGH" },
  { id: "88", option: "B.S.M. KAISERBAGH" },
  { id: "89", option: "B.S.M AWADH" },
  { id: "90", option: "MEERUT" },
  { id: "91", option: "GARH" },
  { id: "92", option: "BARAUT" },
  { id: "93", option: "SOHRABGATE" },
  { id: "94", option: "BHAISALI" },
  { id: "95", option: "MORADABAD" },
  { id: "96", option: "PITALNAGRI" },
  { id: "97", option: "RAMPUR" },
  { id: "98", option: "BIJNOUR" },
  { id: "99", option: "NAJIBABAD" },
  { id: "100", option: "DHAMPUR" },
  { id: "101", option: "CHANDPUR" },
  { id: "102", option: "AMROHA" },
  { id: "103", option: "GREATER NOIDA" },
  { id: "104", option: "NOIDA" },
  { id: "105", option: "ZERO ROAD" },
  { id: "106", option: "PRATAP GARH" },
  { id: "107", option: "MIRZAPUR" },
  { id: "108", option: "LEADER ROAD" },
  { id: "109", option: "CIVIL LINE" },
  { id: "110", option: "LALGANJ" },
  { id: "111", option: "BADSHAHPUR" },
  { id: "112", option: "PRAYAG" },
  { id: "113", option: "SHAMLI" },
  { id: "114", option: "GANGOH" },
  { id: "115", option: "CHHUTMALPUR" },
  { id: "116", option: "KHATAULI" },
  { id: "117", option: "MUZAFFER NAGAR" },
  { id: "118", option: "SAHARANPUR" },
  { id: "119", option: "VARANASI (R) GRAMIN" },
  { id: "120", option: "GHAZIPUR" },
  { id: "121", option: "VINDHYA NAGAR" },
  { id: "122", option: "KASHI" },
  { id: "123", option: "CHANDAULI" },
  { id: "124", option: "CANTT DEPOT" },
  { id: "125", option: "JAUNPUR" },
  { id: "126", option: "SONBHADRA" },
];

const sittingConfiguration1 = [
  { id: "1", option: "AC Sleeper (2+1)" },
  { id: "2", option: "AC Seater (2+2)" },
  { id: "3", option: "A/C Seater / Sleeper (2+1)" },
  { id: "4", option: "A/C Seater / Sleeper (2+2)" },
  { id: "5", option: "Non A/C Seater / Sleeper (2+1)" },
  { id: "6", option: "Non A/C Seater / Sleeper (2+2)" },
  { id: "7", option: "Non A/C Sleeper (2+1)" },
  { id: "8", option: "Non A/c Seater (2+1)" },
  { id: "9", option: "Non A/c Seater (2+2)" },
  { id: "10", option: "Non A/c Seater (2+3)" },
];
const specificationsData = [
  {
    left: { title: "Dimensions", para: "Vehicle Dimensions" },
    right: [
      {
        block_type: "field-type-four",
        name1: "dimensionsWidth",
        input_type1: "number",
        labelName1: "Width",
        placeholder1: "Enter Width",
        rightText1: "mm",
        name2: "dimensionsHeight",
        input_type2: "number",
        labelName2: "Height",
        placeholder2: "Enter Height",
        rightText2: "mm",
        name3: "dimensionsLength",
        input_type3: "number",
        labelName3: "Length",
        placeholder3: "Enter Length",
        rightText3: "mm",
      },
      {
        block_type: "field-type-four",
        name1: "dimensionsInteriorVolume",
        input_type1: "number",
        labelName1: "Interior Volume",
        placeholder1: "Enter Interior Volume",
        rightText1: "mm3",
        name2: "dimensionsPassengerVolume",
        input_type2: "number",
        labelName2: "Passenger Volume",
        placeholder2: "Enter Passenger Volume",
        rightText2: "mm3",
        name3: "dimensionsCargoVolume",
        input_type3: "number",
        labelName3: "Cargo Volume",
        placeholder3: "Enter Cargo Volume",
        rightText3: "mm3",
      },
      {
        block_type: "field-type-five",
        name1: "dimensionsGroundClearance",
        input_type1: "number",
        labelName1: "Ground Clearance",
        placeholder1: "Enter Ground Clearance",
        rightText1: "mm",
        name2: "dimensionsBedLength",
        input_type2: "number",
        labelName2: "Bed Length",
        placeholder2: "Enter Bed Length",
        rightText2: "mm",
      },
    ],
  },
  {
    left: { title: "Weight", para: "Vehicle Weight" },
    right: [
      {
        block_type: "field-type-five",
        name1: "weightCurbWeight",
        input_type1: "textField",
        labelName1: "Curb Weight",
        placeholder1: "Enter Curb Weight",
        rightText1: "kg",
        name2: "weightGrossVehicleWeight",
        input_type2: "textField",
        labelName2: "Gross Vehicle Weight Rating",
        placeholder2: "Enter Vehicle Weight",
        rightText2: "kg",
      },
    ],
  },
  {
    left: { title: "Performance", para: "Vehicle Performance" },
    right: [
      {
        block_type: "field-type-five",
        name1: "performanceTowingCapacity",
        input_type1: "textField",
        labelName1: "Towing Capacity",
        placeholder1: "Enter Towing Capacity",
        rightText1: "kg",
        name2: "performanceMaxPayload",
        input_type2: "textField",
        labelName2: "Max Payload",
        placeholder2: "Enter Max Payload",
        rightText2: "kg",
      },
    ],
  },
  {
    left: { title: "Fuel", para: "Vehicle Fuel Information" },
    right: [
      {
        block_type: "field-type-five",
        name1: "fuelMileageCity",
        input_type1: "textField",
        labelName1: "Mileage (City)",
        placeholder1: "Enter Mileage (City)",
        rightText1: "kmpl",
        name2: "fuelMileageHighway",
        input_type2: "textField",
        labelName2: "Mileage (Highway)",
        placeholder2: "Enter Mileage (Highway)",
        rightText2: "kmpl",
      },
      {
        block_type: "field-type-five",
        name1: "fuelCapacityTank1",
        input_type1: "textField",
        labelName1: "Capacity (Tank 1)",
        placeholder1: "Enter Capacity (Tank 1)",
        rightText1: "it",
        name2: "fuelCapacityTank2",
        input_type2: "textField",
        labelName2: "Capacity (Tank 2)",
        placeholder2: "Enter Capacity (Tank 2)",
        rightText2: "it",
      },
      {
        block_type: "field-type-five",
        name1: "fuelCngCapacity",
        input_type1: "textField",
        labelName1: "CNG Capacity",
        placeholder1: "Enter CNG Capacity",
        rightText1: "kg",
        name2: "fuelBatteryCapacity",
        input_type2: "textField",
        labelName2: "Battery Capacity",
        placeholder2: "Enter Battery Capacity",
        rightText2: "mAH",
      },
    ],
  },
  {
    left: { title: "Oil", para: "Vehicle Oil" },
    right: [
      {
        block_type: "field-type-nine",
        name1: "oilCapacity",
        input_type1: "textField",
        labelName1: "Oil Capacity",
        placeholder1: "Enter Oil Capacity",
        rightText1: "it",
      },
    ],
  },
  {
    left: { title: "Engine", para: "Vehicle Engine Information" },
    right: [
      {
        block_type: "field-type-four",
        name1: "engineSummary",
        input_type1: "textField",
        labelName1: "Engine Summary",
        placeholder1: "Enter Engine Summary",
        name2: "engineBrand",
        input_type2: "textField",
        labelName2: "Engine Brand",
        placeholder2: "Select Engine Brand",
        name3: "engineCompression",
        input_type3: "textField",
        labelName3: "Compression",
        placeholder3: "Enter Compression",
      },
      {
        block_type: "field-type-four",
        name1: "engineCylinders",
        input_type1: "textField",
        labelName1: "Cylinders",
        placeholder1: "Enter Cylinders",
        name2: "engineDisplacement",
        input_type2: "textField",
        labelName2: "Displacement",
        placeholder2: "Enter Displacement",
        name3: "engineFuelInduction",
        input_type3: "textField",
        labelName3: "Fuel Induction",
        placeholder3: "Enter Fuel Induction",
      },
      {
        block_type: "field-type-four",
        name1: "engineMaxHp",
        input_type1: "textField",
        labelName1: "Max HP",
        placeholder1: "Enter Max HP",
        name2: "engineMaxTorque",
        input_type2: "textField",
        labelName2: "Max Torque",
        placeholder2: "Enter Max Torque",
        name3: "engineValves",
        input_type3: "textField",
        labelName3: "Valves",
        placeholder3: "Enter Valves",
      },
    ],
  },
  {
    left: { title: "Transmission", para: "Vehicle Transmission Information" },
    right: [
      {
        block_type: "field-type-five",
        name1: "trnasmisssionType",
        input_type1: "textField",
        labelName1: "Transmission Type",
        placeholder1: "Select Transmission Type",
        name2: "trnasmisssionGear",
        input_type2: "textField",
        labelName2: "Transmission Gears",
        placeholder2: "Enter Transmission Gear",
      },
      {
        block_type: "field-type-one",
        name1: "trnasmisssionDescription",
        input_type: "textarea",
        labelName: "Transmission Description",
        placeholder: "Enter Description",
      },
    ],
  },
  {
    left: {
      title: "Wheels & Tires",
      para: "Vehicle Drive Information",
      title1: "Front",
      para1: "Vehicle Front Tyre Information",
      title2: "Rear",
      para2: "Vehicle Rear Tyre Information",
    },
    right: [
      {
        block_type: "field-type-four",
        name1: "driveType",
        input_type1: "textField",
        isDropDown1: [{ option: "option1" }, { option: "option2" }],
        labelName1: "Drive Type",
        placeholder1: "Select",
        name2: "brakingSystem",
        input_type2: "textField",
        isDropDown2: [{ option: "option1" }, { option: "option2" }],
        labelName2: "Braking System",
        placeholder2: "Select",
        name3: "wheelBase",
        input_type3: "textField",
        labelName3: "Wheelbase",
        placeholder3: "Enter",
      },
      {
        block_type: "field-type-ten",
        leftSection: [
          {
            block_type: "field-type-six",
            name1: "FrontTrackWidth",
            input_type1: "textField",
            labelName1: "Track Width",
            placeholder1: "Enter",
            name2: "FrontWheelDiameter",
            input_type2: "textField",
            labelName2: "Wheel Diameter",
            placeholder2: "Enter",
          },
          {
            block_type: "field-type-six",
            name1: "FrontTyreType",
            input_type1: "textField",
            labelName1: "Tire Type",
            placeholder1: "Enter",
            name2: "FrontTyrePSI",
            input_type2: "textField",
            labelName2: "Tire PSI",
            placeholder2: "Enter",
          },
          {
            block_type: "field-type-six",
            name1: "RearTrackWidth",
            input_type1: "textField",
            labelName1: "Track Width",
            placeholder1: "Enter",
            name2: "RearWheelDiameter",
            input_type2: "textField",
            labelName2: "Wheel Diameter",
            placeholder2: "Enter",
          },
          {
            block_type: "field-type-six",
            name1: "RearTyreType",
            input_type1: "textField",
            labelName1: "Tire Type",
            placeholder1: "Enter",
            name2: "RearTyrePSI",
            input_type2: "textField",
            labelName2: "Tire PSI",
            placeholder2: "Enter",
          },
        ],
        rightSlide: [],
      },
    ],
  },
];
const lifecycleData = [
  {
    left: { title: "In-Service", para: "Vehicle Service Start Information" },
    right: [
      {
        block_type: "field-type-one",
        input_type: "date",
        labelName: "In-Service Date",
        name: "inServiceDate",
        placeholder: "Enter In-Service Date",
        bottomLabel: "Date when vehicle entered active fleet service",
      },
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        labelName: "In-Service Odometer",
        name: "inServiceOdometer",
        placeholder: "Enter In-Service Odometer",
        bottomLabel: "Odometer reading on in-service date",
      },
    ],
  },
  {
    left: {
      title: "Life Estimation",
      para: "Vehicle Life Estimation Information",
    },
    right: [
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        name: "estimatedSeviceLifeMonths",
        labelName: "Estimated Serivce Life (Months)",
        placeholder: "Enter Estimated Serivce Life (Months)",
        bottomLabel:
          "Number of months vehicle is expected to be in active fleet service",
      },
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        name: "estimatedSeviceLifeOdometer",
        labelName: "Estimated Serivce Life (Odometer)",
        placeholder: "Enter Estimated Service Life (Odometer)",
        bottomLabel:
          "Primary meter value vehicle is expected to use/run before retiring from fleet service",
      },
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        name: "estimatedResaleValue",
        labelName: "Estimated Resale Value",
        placeholder: "Enter Estimated Resale Value",
        bottomLabel:
          "Amount expected to be obtained after retirement and sale/disposal (less any associated costs)",
      },
    ],
  },
  {
    left: {
      title: "Out-of-Service",
      para: "Vehicle Out-of-Service Information",
    },
    right: [
      {
        block_type: "field-type-one",
        input_type: "checkbox",
        name: "markOut",
        labelName: "Mark Out of Service",
        placeholder: "Enter Out-of-Service Date",
      },
      {
        block_type: "field-type-one",
        input_type: "date",
        labelName: "Out-of-Service Date",
        name: "outOfServiceDate",
        placeholder: "Enter Out-of-Service Date",
        bottomLabel: "Date vehicle was retired from fleet service",
      },
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        name: "outOfServiceOdometer",
        labelName: "Out-of-Service Odometer",
        placeholder: "Enter Out-of-Service Odometer",
        bottomLabel: "Final odometer reading on out-of-service date",
      },
    ],
  },
];
const MaintenanceData = [
  {
    left: {
      title: "Maintenance",
      para: "Vehicle Maintenance Schedule Settings",
    },
    right: {
      title: "Choose a Vehicle Service Program",
      para: "Service Programs automatically manage Service Reminders for Vehicles that share common preventative maintenance needs.",
      fields: [
        {
          block_type: "field-type-one",
          input_type: "textFieldField",
          labelName: "In-Service Date",
          name: "inServiceDate",
          placeholder: "Enter In-Service Date",
        },
        {
          block_type: "field-type-one",
          input_type: "textFieldField",
          labelName: "In-Service Odometer",
          name: "inServiceOdometer",
          placeholder: "Enter In-Service Odometer",
        },
      ],
    },
  },
];
const FinancialData = [
  {
    left: {
      title: "Purchase Detail",
      para: "Vehicle Service Start Information",
    },
    right: [
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        labelName: "Purchase Vendor",
        name: "purchaseVendor",
        placeholder: "Select Purchase Vendor",
      },
      {
        block_type: "field-type-two",
        input_type1: "date",
        name1: "purchaseDate",
        labelName1: "Purchase Date",
        placeholder1: "Purchase Date",
        input_type2: "number",
        name2: "purchasePrice",
        labelName2: "Purchase Price",
        placeholder2: "Enter Purchase Price",
      },
      {
        block_type: "field-type-one",
        input_type: "textFieldField",
        labelName: "Odometer",
        name: "purchaseOdometer",
        placeholder: "Enter Odometer",
      },
      {
        block_type: "field-type-one",
        input_type: "textarea",
        labelName: "Notes",
        name: "purchaseNotes",
        placeholder: "Enter Notes",
      },
    ],
  },
];
const LoanFields = [
  {
    block_type: "field-type-one",
    input_type: "textFieldField",
    labelName: "Lender",
    name: "lender",
    placeholder: "Select Lender",
  },
  {
    block_type: "field-type-two",
    input_type1: "date",
    name1: "dateofLoan",
    labelName1: "Date of Loan",
    placeholder1: "",
    input_type2: "text",
    name2: "amountOfLoan",
    labelName2: "Amount of Loan",
    placeholder2: "Enter Amount of Loan",
  },
  {
    block_type: "field-type-two",
    input_type1: "text",
    name1: "rateOfInterest",
    labelName1: "Annual Rate Of Interest(ROI)",
    placeholder1: "Enter Annual Rate of Interest",
    input_type2: "text",
    name2: "downPayment",
    labelName2: "Down Payment",
    placeholder2: "Enter Down Payment Amount",
  },
  {
    block_type: "field-type-two",
    input_type1: "date",
    name1: "firstPaymentDate",
    labelName1: "First Payment Date",
    placeholder1: "",
    input_type2: "number",
    name2: "monthlyPayment",
    labelName2: "Monthly Payment",
    placeholder2: "Enter Monthly Payment",
  },
  {
    block_type: "field-type-two",
    input_type1: "text",
    name1: "numberOfPayments",
    labelName1: "Number of Payments / Instalments",
    placeholder1: "Enter Number of Payments",
    input_type2: "date",
    name2: "loanEndDate",
    labelName2: "Loan End Date",
    placeholder2: "",
  },
  {
    block_type: "field-type-one",
    input_type: "text",
    labelName: "Account Number",
    name: "accountNumber",
    placeholder: "Enter Account Number",
  },
  {
    block_type: "field-type-one",
    input_type: "textarea",
    labelName: "Notes",
    name: "loanNotes",
    placeholder: "Enter Notes",
  },
  {
    block_type: "checkbox",
    input_type: "checkbox",
    name: "loanGenerateExpenses",
    labelName: "Generate Expenses",
    placeholder:
      "Automatically generate expenses entries for payment for this loan/lease.",
  },
];

const LeaseFields = [
  {
    block_type: "field-type-one",
    input_type: "textField",
    labelName: "Vendor",
    name: "vendor",
    placeholder: "Select Vender",
  },
  {
    block_type: "field-type-two",
    input_type1: "date",
    name1: "dateofLease",
    labelName1: "Date of Lease",
    placeholder1: "",
    input_type2: "textField",
    name2: "capitalizedCost",
    labelName2: "Capitalized Cost",
    placeholder2: "Enter Capitalized Cost",
  },
  {
    block_type: "field-type-one",
    input_type: "text",
    labelName: "Down Payment",
    name: "downPayment",
    placeholder: "Enter Down Payment",
  },
  {
    block_type: "field-type-two",
    input_type1: "date",
    name1: "firstPaymentDate",
    labelName1: "First Payment Date",
    placeholder1: "",
    input_type2: "text",
    name2: "monthlyPayment",
    labelName2: "Monthly Payment",
    placeholder2: "Enter Monthly Payment",
  },
  {
    block_type: "field-type-two",
    input_type1: " number",
    name1: "instalments",
    labelName1: "Number of Payments / Instalments",
    placeholder1: "Enter Number of Payments",
    input_type2: "date",
    name2: "leaseEndDate",
    labelName2: "lease End Date",
    placeholder2: "",
  },
  {
    block_type: "field-type-one",
    input_type: "number",
    labelName: "Residual Value",
    name: "residualValue",
    placeholder: "Enter Residual Value",
  },
  {
    block_type: "field-type-two",
    input_type1: "text",
    name1: "contractMileageLimit",
    labelName1: "Contract Mileage Limit",
    placeholder1: "Enter Contract Mileage Limit",
    input_type2: "text",
    name2: "excessMileageCharge",
    labelName2: "Excess Mileage Charge",
    placeholder2: "Enter Excess Mileage Charge",
  },
  {
    block_type: "field-type-one",
    input_type: "text",
    labelName: "Lease Number",
    name: "leaseNumber",
    placeholder: "Enter Lease Number",
  },
  {
    block_type: "field-type-one",
    input_type: "textarea",
    labelName: "Notes",
    name: "leaseNotes",
    placeholder: "Enter Notes",
  },
  {
    block_type: "checkbox",
    input_type: "checkbox",
    name: "leaseGenerateExpenses",
    labelName: "Generate Expenses",
    placeholder:
      "Automatically generate expenses entries for payment for this loan/lease.",
  },
];
export {
  indianStates,
  regionData,
  depotOptions,
  sittingConfiguration1,
  specificationsData,
  lifecycleData,
  MaintenanceData,
  LeaseFields,
  LoanFields,
  FinancialData,
};
